# timeout
timeout = "1200s"
# your website url
baseURL = 'https://giography.vercel.app/'
# website title
title = 'giography'
# don't touch this
disableKinds = [ "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
# relativeURLs = true
# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'en'
[params]
bundled = true

# theme as module
[module]
# replacements = "github.com/Sped0n/bridget/v2 -> ../.." # deploy with local dir  WARN: delete this line if you want to deploy with git
[[module.imports]]
path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!
